function y = filter10(x)
%FILTER10 对输入 x 进行滤波并返回输出 y。

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 13-May-2021 11:36:11

%#codegen

% 要通过此函数生成 C/C++ 代码，请使用 codegen 命令。有关详细信息，请键入 'help codegen'。

persistent Hd;

if isempty(Hd)
    
    % 设计滤波器系数时使用了以下代码:
    % % Equiripple Lowpass filter designed using the FIRPM function.
    %
    % % All frequency values are normalized to 1.
    %
    % N     = 10;   % Order
    % Fpass = 0.5;  % Passband Frequency
    % Fstop = 0.8;  % Stopband Frequency
    % Wpass = 1;    % Passband Weight
    % Wstop = 50;   % Stopband Weight
    % dens  = 20;   % Density Factor
    %
    % % Calculate the coefficients using the FIRPM function.
    % b  = firpm(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop], {dens});
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [0.0328167719802339 0.0619947055114297 ...
        -0.0521127678851875 -0.0843121169138371 0.295702701484053 ...
        0.599603883398042 0.295702701484053 -0.0843121169138371 ...
        -0.0521127678851875 0.0619947055114297 0.0328167719802339]);
end

y = step(Hd,double(x));


% [EOF]
