function [nrSRSParameters] = nrSRSParametersInit()

%%---
%
% SRS_Resource.freqDomainPosition;
% SRS_Resource.freqHopping.b_hop = 0;
% SRS_Resource.freqHopping.bSRS = 0;
% SRS_Resource.freqHopping;cSRS = 8;
% SRS_Resource.freqDomainShift = 0;
% SRS_Resource.transmissionComb.combOffset = 1;
% SRS_Resource.transmissionComb.n2n4 = 2;
% NSRS_ap = 4;    %up tp configuration
% pi      = 1001; %1001~1003

port1000_table = struct (...
    'w_k_0', [+1 +1 +1  +1 +1  +1 +1  +1],...
    'w_k_1', [1, -1, 1, -1, 1, -1, 1, -1],...
    'delta', [0 0 1 1 0 0 1 1]);

sysConst = struct (...
    'MaxRB', 275,...
    'Mu', 1,...
    'FFTSize', 4096,...
    'NRB_SC', 12,...
    'NSRS_ap', 4,...
    'pi', [1001, 1002, 1003, 1004]);
transmissionComb = struct (...
    'combOffset', 1,...
    'n2n4', 2);
freqHopping = struct (...
    'b_hop', 0,...
    'bSRS', 0,...
    'cSRS', 63);
SRS_Resource = struct(...
    'freqDomainPosition', 0,...
    'freqDomainShift', 0,...
    'freqHopping', freqHopping,...
    'transmissionComb', transmissionComb);
nrSRSParameters = struct(...
    'sysConst', sysConst,...
    'SRS_Resource', SRS_Resource,...
    'port1000_table', port1000_table);

end

